---
title: "yarrow"
output: html_notebook
---

```{r}
library(data.table)
library(stringr)
library(gtools)
library(R6)

library(profvis)
library(tictoc)
```
```{r}
Stack <- R6Class("Stack", 
                 private = list(
                   stack = vector(mode = "integer")
                 ),
                 public = list(
                   initialize = \(with = NULL) {
                     private$stack <- c(with)
                   }
                 ),
                 active = list(
                   p = \(value) { #push/pop
                     if (missing(value)) { #pop
                       if (length(private$stack) < 1) {
                         stop("Cannot pop an empty stack.",
                              .call = FALSE)
                       } else {
                         ret <- private$stack[[1]]
                         private$stack <- private$stack[-1]
                         ret
                       }
                     } else { #push
                       private$stack <- append(value,
                                               private$stack)
                       invisible(self)
                     }
                   }
                 ))

Queue <- R6Class("Queue",
                 private = list(
                   queue = vector(mode = "list")
                 ),
                 public = list(
                   initialize = \(with = NULL) {
                     private$queue <- c(with)
                   }
                 ),
                 active = list(
                   print = \(value) {
                     if (missing(value)) {
                       q <- capture.output(cat(
                         as.character(private$queue),
                         sep = ""))
                       private$queue <- list()
                       q
                     } else {
                       private$queue <- append(
                         private$queue, gtools::chr(
                           as.integer(value))
                       )
                     }
                   }
                 ))
```
```{r}
printqueue <- Queue$new()

printqueue$print <- 87

printqueue$print

printqueue$print <- c(87, 71)
printqueue$print
```
```{r}
stack <- Stack$new()

stack$p <- 98
stack$p <- 101
stack$p <- 1402

stack$p
stack$p
stack$p
```
Note: `eval(str2lang(str))`

```{r}



a <- memories[doing + 1]
if (perform == 19) {
  printqueue$print <- a #1-index doing
  doing <<- doing + 2 
  next #figure out how to make next behavior consistent 
} else {
  if (!(any(1:18 == perform))) {
    printqueue$print #print before halt, noop, malformed command, or in 
  }
  do.call(what = .subset2(opcodes, perform), args = args)
}

```

Consider: `paste0("machine$", opcodes[[6]], as.character(args)) |> str2lang() |> eval()`? (Requires retrofitting all Machine arguments to take `\(...)` and discard as needed, which, like, I've done it before.)

