---
title: "vm - xenon"
author: "Cyrus"
output: html_notebook
---

```{r setup}
library(data.table) #table
library(stringr) #string wrangling

library(tictoc) #timer
library(profvis) #profiling

##build constants:

## use for bitwise not 
bin_const <- 2^(0:14)

## use for less dyslexia mod errors
modulo <- 32768
magic <- 32776 ## total number of possible locations 

## use for finding opcodes 
opnames <- c(
  "op_00_halt", "op_01_set", "op_02_push",
  "op_03_pop", "op_04_eq", "op_05_gt", 
  "op_06_jmp", "op_07_jt", "op_08_jf", "op_09_add",
  "op_10_mult", "op_11_mod", "op_12_and",
  "op_13_or", "op_14_not", "op_15_rmem",
  "op_16_wmem", "op_17_call", "op_18_ret",
  "op_19_out", "op_20_in", "op_21_noop")

#get commands
raw <- file("./materiel/challenge.bin", "rb") 
    ## rb = "read binary"
cmdlist <- readBin(raw, integer(), n = modulo, 
      ### n kind of irrelevant but must be arbitrarily specified; assume program is no longer than memory 
      ### the rest of these are very important 
                   size = 2, endian = "little",
                   signed = FALSE)
close(raw)
```

```{r utility_funcs}
## General-purpose functions
#### called by the opcodes for repetitive tasks

finish <- \(loc, n = 0) { #expect z-indexed
  line <- loc + 1 ### location of current z 
  doing <<- (line + n) ### doubles for moving to next z 
  memory[(line):(doing), done := TRUE] ### mark done 
  return(invisible(NULL))
}

write_loc <- \(value, to = NULL) {
  if (is.null(to)) {
    to <- work[1] ### default to assuming  that
      ### we may want to write to the register 
  }
  if (to >= modulo) { 
    ### track register due to nonzero reg error
    reglog <- paste0("**Register change:** writing value = ",
                     value, " to = ", to)
    writeLines(reglog)
    loglines <- append(loglines, 
                       c(" ", "---", " ", reglog, " "))
  }
  memory[z %in% (to), cmd := (value)] ### update address
  return(invisible(NULL))
}

pop_stack <- \() {
  stopifnot(length(stack) > 0) 
  x <- stack[1] 
  stack <<- stack[-1] ### superassign pop top off stack
  stacklog <- paste0("Popped value x = ", x, " off of the stack. Remaining stack contents: ", capture.output(cat(as.character(stack))))
  print(stacklog)
  loglines <<- append(loglines, c(" ", stacklog, " "))
  x ### return
}
```

```{r dispatcheR}
## Controller
#run within while loop for doing < 32768
logbrk <- c(" ", "---", " ")

dispatcheR <- \() {
  perform <- memory[z == (doing), cmd] 
  work <<- memory[z %in% ((doing)+1):((doing)+3), cmd] 
  args <- lapply(work, ### read register values... 
                 \(x) { if (x >= modulo) { ### iff reg memloc
                     y <- memory[z == (x), cmd]
                   } else { y <- x } })
  if ((length(printqueue) > 0) & 
      ### always print before halt or noop
       (perform == 0 | perform == 21) |
      (length(printqueue) > 50) ### arbitrary cutoff here 
      ### print if not about to move elsewhere 
        & !(perform %in% c(6:8, 17:19))) { 
    msg <- c(capture.output(cat
                            (printqueue, sep = "")))
    writeLines(msg, con = stdout())
    loglines <<- append(loglines, 
                        c(logbrk, msg, " "))
    printqueue <<- c()
  } 
  if (!(perform %in% c(0, 19, 21))) { 
    ### no argument logging for print,  noop, or halt
    track <- c(paste0("Doing: ", 
                  as.character(
                   .subset2(opnames, (perform + 1))), 
                   " at z = ", doing), 
               (paste0("... [work] contains:",
                      capture.output(
                        cat(as.character(work))))))
    loglines <<- append(loglines, c(logbrk, track))
    writeLines(track)
    if (identical(args, work)) {
      alog <- "... and [args] match [work]."
    } else {
      alog <- (paste0("... [args] contains:",
                        capture.output(
                          cat(as.character(args)))))
    }
    writeLines(alog)
    loglines <<- append(loglines, c(alog, logbrk))
    print("...")
  }
  stopifnot(perform <= 21) #stop for illegal commands
  if (perform == 0) {
    op_00_halt()
#    break ### check if break is needed still 
  } else {
    do.call(what = 
              .subset2(opnames, (perform + 1)), 
            args = as.list(args))
  }
  return(invisible(NULL))
}
```

```{r opcodes}
op_00_halt <- \(...) { 
  writeLines(paste0(
    "ALERT :: Halting at z = ", doing, "!"))
  loglines <<- append(
    loglines, c(" ", "---", " ", 
    (paste0(
      "**HALT ::** Program halted by z-index `",
            doing, "`")), " "))
  finish(doing)
  doing <<- modulo
  lfn <- paste0("./logs/xenon_loglines_", 
                     as.integer(Sys.time()), ".md")
  fwrite(list(loglines), file = lfn)
  writeLines(c(
    "Counter set to 32768; execution ended. Default logs...", 
    paste0("...have been saved to ", lfn)))
  return(invisible(NULL))
}

op_01_set <- \(...) {
  b <- ..2
  write_loc(value = b)
  finish(doing, 2)
  return(invisible(NULL))
}

op_02_push <- \(...) {
  a <- ..1
  stack <<- append(a, stack)
  finish(doing, 1)
  return(invisible(NULL))
}

op_03_pop <- \(...) {
  val <- pop_stack()
  write_loc(value = val)
  finish(doing, 1)
  return(invisible(NULL))
}

op_04_eq <- \(...) {
  b <- ..2
  c <- ..3
  print(paste0("Eq trying: ", b, "==", c))
  if (b == c) {
    write_loc(value = 1)
  } else {
    write_loc(value = 0)
  }
  finish(doing, 3)
  return(invisible(NULL))
}

op_05_gt <- \(...) {
  b <- ..2
  c <- ..3
  print(paste0("Gt trying: ", b, " > ", c))
  if (isTRUE(b > c)) {
    write_loc(value = 1)
  } else {
    write_loc(value = 0)
  }
  finish(doing, 3)
  return(invisible(NULL))
}

op_06_jmp <- \(...) {
  a <- ..1
  finish(doing, 1)
  doing <<- a 
  return(invisible(NULL))
}

op_07_jt <- \(...) {
  a <- ..1
  b <- ..2
  finish(doing, 2)
  if (isTRUE(a > 0)) {
    doing <<- b
  }
  return(invisible(NULL))
}

op_08_jf <- \(...) {
  a <- ..1
  b <- ..2
  finish(doing, 2)
  if (a == 0) {
    doing <<- b
  } 
  return(invisible(NULL))
} 

op_09_add <- \(...) {
  b <- ..2
  c <- ..3
  got <- (b + c) %% modulo
  write_loc(value = got)
  finish(doing, 3)
  return(invisible(NULL))
}

op_10_mult <- \(...) {
  b <- ..2
  c <- ..3
  got <- (b * c) %% 32768
  write_loc(value = got)
  finish(doing, 3)
  return(invisible(NULL))
}

op_11_mod <- \(...) {
  b <- ..2
  c <- ..3
  got <- b %% c
  write_loc(value = got)
  finish(doing, 3)
  return(invisible(NULL))
}

op_12_and <- \(...) {
  b <- ..2
  c <- ..3
  bits <- bitwAnd(b, c)
  write_loc(value = bits)
  finish(doing, 3)
  return(invisible(NULL))
}

op_13_or <- \(...) {
  b <- ..2
  c <- ..3
  bits <- bitwOr(b, c)
  write_loc(value = bits)
  finish(doing, 3)
  return(invisible(NULL))
}

op_14_not <- \(...) {
  b <- as.integer(intToBits(..2))[1:15]
  bt <- b == 0
  bits <- sum(bin_const[bt])
  write_loc(value = bits)
  finish(doing, 2)
  return(invisible(NULL))
}

op_15_rmem <- \(...) {
  b <- memory[z == (..2), cmd] 
  write_loc(value = b)
  finish(doing, 2)
  return(invisible(NULL))
}

op_16_wmem <- \(...) {
  a <- ..1
  b <- ..2
  write_loc(value = b, to = a)
  finish(doing, 2)
  return(invisible(NULL))
}

op_17_call <- \(...) {
  a <- ..1
  finish(doing, 1) 
  stack <<- append(doing, stack) 
  doing <<- a #update doing again to find real destination
  return(invisible(NULL))
}

op_18_ret <- \(...) {
  if (isTRUE(length(stack) < 1)) {
    loglines <<- append( ## note error.
      loglines, c(" ", (paste0(
      "!!:: `ret` (opcode 18) at `doing` = `",
      doing, 
      "` found an empty stack; calling halt.")), 
      " "))
    op_00_halt()
  } else {
    finish(doing, 0)
    top <- pop_stack()
    if (top >= modulo) {
      doing <<- memory[z == (top), cmd]
    } else {
      doing <<- top 
    }
  }
  return(invisible(NULL))
}

op_19_out <- \(...) {
  a <- ..1
  ch <- rawToChar(as.raw(a))
  printqueue <<- append(printqueue, ch)
  finish(doing, 1)
  return(invisible(NULL))
}

op_20_in <- \(...) {
  ti <- Sys.time()
  d <- Sys.Date()
  into <<- ..1
  resume <<- doing
  ofn <- paste0("./logs/saves/", d, 
                "_logs_dump.md")
  sfn <- paste0("./logs/saves/", d, 
                "_memloc_", doing, 
                "_into_", ..1, ".csv")
  if (length(stack) > 0) {
    tfn <- paste0("./logs/saves/", d, 
                  "_memloc_", doing, 
                  "_into_", ..1, "_stack.txt")
    tadd <- paste0(c("`, and stack of length ", 
                     length(stack), " (`", 
                     capture.output(cat(as.character(stack), 
                                        sep = ", ")), 
                     "`) to `", tfn))
    fwrite(list(stack), file = tfn)
  } else {
      tadd <- c()
  }
  msg <- c(paste0(ti, " || Saving logs to `", ofn,
                "` with savefile at `", sfn, tadd,
                "` now."), 
           " ", "...", " ", "PROMPT: ", " ",
           capture.output(cat(printqueue, sep = "")),
           " ", "Resume with `go(action = {command}, write = "
           , into, ", finish = ", resume, ")` to continue!")
  writeLines(msg)
  loglines <<- append(loglines, c(" ", "---", " "), msg)
  fwrite(list(loglines), file = ofn)
  fwrite(memory, file = sfn)
  doing <<- modulo
  return(invisible(NULL))
}

op_21_noop <- \(...) {
  writeLines(".....................")
  finish(doing, 0)
  return(invisible(NULL))
}
```

```{r scratch}
scratch <- \() {
  cmdlen <- length(cmdlist)
  memory <<- data.table(
    z = 0:(magic - 1),
    cmd = c(cmdlist, rep(0, (magic - cmdlen))),
    done = c(rep(as.logical(NA), magic)),
    is = c(rep("mem", modulo), rep("reg", 8))
  )
  setkey(memory, z)
}
```

```{r load_save}
restore <- \() {
  if (is.null(sfn)) {
    memory <<- file.choose() |> fread()
  } else {
    memory <<- fread(sfn)
  }
  setkey(memory, z)
}
```

```{r machin}
challengeR <- \(doing = 0, quit = 32768) {
  tic("starting machine...")
  writeLines(paste0("START :: Run starts at ", Sys.time()))
  stopifnot(nrow(memory) >= 1)
  while (doing < quit) {
    if (isFALSE(length(doing) == 1)) {
      stopmsg <- paste0("STOP :: Error: <doing> is ", doing, 
                 ". Setting to 32768 to exit.")
      loglines <<- append(
        loglines, c(" ", "---", " ", stopmsg))
      writeLines(stopmsg)
      doing <<- modulo
    } else {
      dispatcheR()
    }
  }
  if (quit < modulo) {
    writeLines(paste0(
      "QUIT :: Stopped early for <quit> = ", quit))
  }
  fwrite(memory, 
       file = "./logs/xenon_latest_run.csv",
       yaml = TRUE)
  if (length(stack) > 0) {
    fwrite(list(stack),
           file = "./logs/xenon_latest_stack.txt")
  }
  toc()
  writeLines(paste0("STOP :: Run ends at ", Sys.time()))
}
```

```{r interact}
go <- \(action = NA, write = NA, finish = NA) {
  if (is.na(write) & !(is.na(into))) {
    write <- into
  }
  if (is.na(finish) & !is.na(resume)) {
    finish <- resume
  }
  if (is.na(write) | is.na(finish)) {
    ergo <- c(" ", "...", 
              "ERROR :: Cannot execute `go(action = ", 
              action, ", write = ", write, 
              "finish = ", finish, "`.")
    writeLines(ergo)
    break
  } else {
    if (length(printqueue) > 0) {
      cat(printqueue, sep = "")
      printqueue <<- c()
    }
    while (is.na(action)) {
      action <- readline(
        prompt = "Enter command...")
    }
    str <- strsplit(action)
    seq <- seq_along(str) - 1
    chs <- lapply(str, charToRaw)
    write_loc(value = chs, to = seq)
    finish(finish, n = 1)
  }
  return(invisible(NULL))
}
```

```{r goeR}
goeR <- \(action = NA, write = NA, finish = NA) {
  go(action = action, write = write, finish = finish)
  challengeR()
  return(invisible(NULL))
}
```

```{r starteR}
starteR <- \(resume = FALSE, play = FALSE, from = NA, action = NA, write = NA, quit = 32768) {
  if (isTRUE(resume)) {
    restore()
  } else {
    scratch()
  }
  if (!is.na(from) & from < modulo) {
    doing <- from
    if (isTRUE(play)) {
      go(action = action, write = write, finish = from)
    }
  } else {
    doing <- 0
  }
  if (doing > quit) {
    writeLines("Nothing left to do.")
    break
  } else {
    challengeR(doing = doing, quit = quit)
  }
  return(invisible(NULL))
}
```

```{r try_it}
loglines <- c()
stack <- c()
printqueue <- c()
doing <- 0

profvis( { 
    starteR() 
  }, interval = 0.1)
```

```{r manual_logging}
fwrite(list(loglines), 
       file = paste0("./logs/xenon_loglines_", 
                     as.integer(Sys.time()), ".md"))
fwrite(memory, file = paste0(
  "./logs/", as.integer(Sys.time()), ".csv"))
```
